cloudinary/cloudinary-video-player

- src/utils/user-agent.js
- src/video-player.js
> Fix: Disable mouse time display on mobile

- src/index.js
- src/plugins/cloudinary/playlist.js
- src/video-player.js
> Hide 'upcoming-video' component when loop mode is set

- package.json
@mikeys typed `npm install save-dev foo` instead of `npm install --save-dev foo`
https://github.com/cloudinary/cloudinary-video-player/pull/13/files
> remove save-dev dependency

- src/plugins/cloudinary/components/cloudinary-button.js
- src/plugins/cloudinary/components/cloudinary-button.scss
There was no issue with the actual player styles.
We just needed more specific class names.
Now using a global namespace of `vjs-cloudinary-COMPONENT-ELEMENT `.
> CLD-7312-tooltip-logo

- src/plugins/cloudinary/components/cloudinary-button.scss
- src/plugins/context-menu/context-menu.scss
- src/utils/css-prefix.js
@mikeys the logic here is spread across multiple places and `skinClass` functions are being called from many different places.
Please see if this change might break something.
> CLD-7866-default-skin

- src/plugins/cloudinary/components/upcoming-video-overlay.js
This fixes
in players without ads.
`ima` is not initialized so `getAdManager` doesn’t exist.
in this scenario `this.player().ima` is actually a function, this is why it throws the error
> CLD-7899-present-Upcoming-option

- package.json
- webpack/deploy.js
- `npm run deploy` for `stable` version release
- `npm run deploy -- edge` for `edge` version release
Assuming `version: 1.0.3-edge.4`:
- `npm run deploy` will result a version bump to `1.0.3`
- `npm run deploy -- edge` will result a version bump to `1.0.3-edge.5`
Assuming `version: 1.0.3`:
- `npm run deploy` will result a version bump to `1.0.4`
- `npm run deploy -- edge` will result a version bump to `1.0.4-edge.0`
> Version release tooling

- src/plugins/cloudinary/index.js
This builds on top of functionality that was already in place -
`Set the poster dimensions to player dimensions if those are specified` - this worked but completely ignored fluidity and actual player size.
After this change, we set poster dimensions (rounded to 100px) whenever we have a player size and as long as those were not specified explicitly.
> APPS-2793-responsive-poster

- docs/adaptive-streaming.html
- docs/index.html
- src/plugins/cloudinary/index.js
- src/plugins/dash/index.js
- src/plugins/index.js
- src/video-player.js
- yarn.lock
This fixes the `light` version logic so that it does not include Dash. while still keeping the fix to APPS-4585 by @yaniv-li 
I created a sandbox with both version for testing here: https://codesandbox.io/s/amazing-https-bzskq?file=/index.html
> APPS-4585-remove-dash-from-light

- docs/_template.html
- docs/index.html
- docs/poster.html
- src/plugins/cloudinary/index.js
- src/plugins/cloudinary/models/video-source.js
- src/utils/cloudinary.js
- src/video-player.js
This PR fixes an issue in v1.4.1 where setting an Array of poster-transformation would cause our fluid-poster logic to fail (https://codesandbox.io/s/spring-water-iyyqe).
- uses `isKeyInTransformation` instead of dirctly checking `opts.transformation.getValue`
- moved `isKeyInTransformation` to `/src/utils/cloudinary`
- moved `this.fluid(_options.fluid)` initialization so it happens a bit sooner
> APPS-5025-poster-options

- src/plugins/cloudinary/index.js
This fixes an error that is being logged to the console:
> VIDEOJS: ERROR: TypeError: Cannot read property 'contains' of null
at Player.syncState (index.js:399)
at HTMLDivElement.data.dispatcher (video.es.js:1939)
at trigger (video.es.js:2075)
at Player.trigger$1 (video.es.js:2961)
at Player.eval (videojs-per-source-behaviors.es.js:314)
at eval (video.es.js:4666)
`_lastSource` is explicitly set to `null` higher up in the file, so calling `contains` on it causes this error.
Seems to be an easy fix: just ensure it's truthy before running `contains`.
> fix: calling `contains` on `null` in plugins/cloudinary

- src/components/logoButton/logo-button.scss
fixes logo button styles when focused:
probably caused by a VideoJS update
> CLD-1937-cld-logo-btn fix

- docs/components.html
- src/components/recommendations-overlay/recommendations-overlay.js
- src/mixins/playlistable.js
- src/plugins/cloudinary/index.js
This PR fixes the recommendations component not working well in the `light` version.
The issue was brought up in latest QA cycle
https://cloudinary.github.io/cloudinary-video-player/recommendations.html?ver=latest&light=true
> fix recommendations in the light version

- src/video-player.js
Fixes an issue in IE 11 that the big play button disappears after ~60 sec`
> fix big button disappear in IE11

- types/video-player.d.ts
I run into an issue where the low-level customization options with Video.js were ignored in TypeScript.
Video.js option names are expected to be all lowercase.
https://github.com/cloudinary/cloudinary-video-player/blob/a013bc009712a44c34a44d922a809e9840f88a45/src/video-player.js#L132-L137
After modifying the type definition name from "videoJS" to "videojs", the Low-level customization option worked correctly in my environment.
> Fix type declaration name for videojs option

- src/assets/styles/components/interaction-areas.scss
- src/components/interaction-area/interaction-area.const.js
- src/components/interaction-area/interaction-area.utils.js
- src/video-player.js
The developing part for [this task](https://cloudinary.atlassian.net/browse/APPS-10130) was small but it was involved some research with Eran. 
To find the best minimum duration translation time, it's not hard coded in the client, calc by endTime - startTime .
Eran sent me different vtt files (different fps time) to look how is it like on the client.  
The transition duration has been added dynamically 
There is a limitation from the video.js ,  the tracking event is every 250ms
> adding transition to interaction-area item

- .travis.yml
- package.json
- src/assets/styles/components/interaction-areas.scss
- src/assets/styles/mixins/aspect-ratio.scss
- src/plugins/dash/setup-audio-tracks.js
- src/plugins/dash/setup-text-tracks.js
- src/plugins/dash/videojs-dash.js
- yarn.lock
Replacing #325
This time keeping the internal implementation of `videojs-contrib-dash`.
Importing it as a module results in 2 copies of DashJS in the final bundle :(
> APPS-11327-Upgrade-DashJS

- package.json
- webpack/dev.config.js
- webpack/es5.config.js
- yarn.lock
- https://cloudinary.atlassian.net/browse/APPS-12514
update webpack-bundle-analyze to version 4.0.0 remove the needed for ejs
- https://cloudinary.atlassian.net/browse/APPS-12515
I tried to update webpack-dev-server to the next version but it cause problems when running a local serve
> Security blitz

- src/components/playlist/components/playlist-next-button.js
- src/components/playlist/components/upcoming-video-overlay.js
- src/components/playlist/components/upcoming-video-overlay.scss
This PR prevents a situation where the button click propagate to the clickable wrapper element and that caused the click handler to be called twice
Fixes https://cloudinary.atlassian.net/browse/POP-1125
> POP-1125-playlist-next

- docs/cloudinary-analytics-multiple-videos.html
- docs/index.html
- src/components/cld-analytics/cld-analytics.js
Change mechanism of collecting events to base on `Date.now` time instead of `currentTime` of video.
It solves many problems - mostly while seeking video, looping it.
Additionally added `emptied` event listener for interaction areas where source is changed during playing.
> fix: cld analytics events

- README.md
- src/index.js
This PR:
* Adds a default export so you could import the VP as:
1.  `import { videoPlayer } from 'cloudinary-video-player';` or
2. `import cloudinary from 'cloudinary-video-player';`
* Update the README to document a proper way to import the package.
> ME-4306-lazy-load-readme

- src/plugins/index.js
This PR adds `videojs-contrib-ads` to the lazy loaded module, instead of bundling it to the main one
> ME-6552-lazy-ads - lazy load 'videojs-contrib-ads'

- src/components/cld-analytics/cld-analytics.js
Prevent sending undefined as cloud name in cld analytics
> fix: prevent sending undefined cloud name from cld analytics

- src/assets/styles/main.scss
previous VP version, no problem - https://codesandbox.io/s/dank-tree-9lxj3s?file=/index.html
latest VP version, poster does not cover - https://codesandbox.io/s/clever-blackwell-x79g7p?file=/index.html
This happened because to poster implementation changed from background-image to an actual `<img>` tag
This PR fixes it so that the new poster structure will behave the same
> ME-7161-poster-black-bars

- src/plugins/paced-transcript/index.js
This change fixes an issue that came up in QA where the textTrack was not always being added because of a race-condition with the video source
> ME-14358-paced-transcript-event

- src/video-player.js
There was a wrong check for a `controlBar`, which caused the selector to not show, now that we don't pass the `controlBar` config object by default.
This PR fixes that
> ME-14916-picture-in-picture-fix

- src/plugins/playlist/playlist.js
- src/video-player.js
This PR fixes an issue that seem to be introduced in 1.10.2 when we introduced `f_auto` as default
https://cloudinary.github.io/cloudinary-video-player/playlist-by-tag-captions.html?ver=latest&min=true
> ME-15490-playlist-by-tag

- src/assets/styles/main.scss
- src/plugins/chapters/chapters.js
This PR fixes a similar issue to the one we saw in the paced-subtitles feature.
When programmatically creating text-tracks, Safari needs to wait a cycle for the track to be ready for cues
> ME-15396-chapters-in-Safari

- src/plugins/cloudinary/models/video-source/video-source.const.js
- src/plugins/cloudinary/models/video-source/video-source.js
- src/plugins/cloudinary/models/video-source/video-source.utils.js
- src/utils/cloudinary.js
- test/unit/videoSource.test.js
This PR fixes our mimetypes testing logic.
Until now we were simply using the file extension for non ABR, which was ok for some types but bad for others.
This is now aligned with [videojs mimetypes](https://docs.videojs.com/utils_mimetypes.js.html)
> fix: mimetypes

- src/assets/styles/components/text-tracks.scss
- src/plugins/styled-text-tracks/index.js
- src/plugins/styled-text-tracks/styled-text-tracks.js
- src/plugins/styled-text-tracks/styled-text-tracks.scss
Managed to support most styling properties without disabling nativeTextTracks, so it’s also supported in iOS full screen
What’s supported everywhere - basic low level text styling - i.e. font-family, font-size, color, text-shadow etc, also for highlighted word.
Partially supported - i.e. in all browsers except Safari with nativeTextTracks - mostly position related property - i.e. gravity, position, margin etc
> fix: styled subtitles browser compatibility

- webpack/es6.config.js
Export default profiles as raw json files so they can be imported directly in BFF.
> build: add default profiles json files to build output in es version

- src/utils/get-analytics-player-options.js
This PR adds `debug` mode to internal analytics
> fix: debug mode analytics (ME-15925)

- src/utils/cloudinary.js
This PR introduces a small change to the transcript fetching logic.
Previously we fetched transcript only if `maxWords` or `wordHighlight` were configured, but in reality you might want the transcript without any of those.
This changes the condition so that if a text-track is configured without specifying a `src` it will try fetching the transcript file
> fix: text track with no src should fall-back to transcript

- src/plugins/cloudinary/models/video-source/video-source.js
- src/video-player.js
This PR adds the required changes for live streams handling
> fix: handle live streams

- test/e2e/specs/linksConsoleErrorsEsmPage.spec.ts
When running the ESM pages we see that sometimes an error of "Failed to load resource: the server responded with a status of 404 ()" is thrown for some .svg from http://vite.com. It was now added to ignore errors list.
> vp test: adding error message to ignore errors for ESM pages

- docs/es-modules/profiles.html
- docs/es-modules/raw-url.html
- docs/profiles.html
- docs/raw-url.html
- src/index.es.js
- src/index.js
- src/index.videoPlayerWithProfile.js
- src/player.js
- test/e2e/specs/linksConsolErros.spec.ts
- test/e2e/specs/linksConsoleErrorsEsmPage.spec.ts
- webpack/es6.config.js
* Add url template for video player profiles with support for staging env
* Remove deprecated method `videoPlayerWithProfile`
> feat: add url template for video player profiles

- test/e2e/specs/mainPageVideoIsPlaying.spec.ts
Modify test description to more clear description
> vp test: modify test description

- docs/subtitles-and-captions.html
- src/utils/cloudinary.js
- src/utils/get-analytics-player-options.js
This Pr adds the ability to explicitly configure transcript source URLs
i.e.
```
captions: {
label: "Lincoln's Transcript",
url: 'https://res.cloudinary.com/demo/raw/upload/lincoln.transcript',
wordHighlight: true,
maxWords: 8,
}
```
> feat: allow transcript url

- docs/es-modules/subtitles-and-captions.html
- docs/subtitles-and-captions.html
- src/plugins/paced-transcript/index.js
This PR adds the ability to auto-fetch transcripts based on language codes
> feat: auto-fetch transcripts from language

- docs/es-modules/subtitles-and-captions.html
- docs/subtitles-and-captions.html
- package-lock.json
- package.json
- src/plugins/index.js
- src/plugins/paced-transcript/index.js
- src/plugins/srt-text-tracks/index.js
- src/plugins/srt-text-tracks/srt-text-tracks.js
- src/utils/cloudinary.js
- src/utils/get-analytics-player-options.js
This PR introduces a new `srtTextTracks` plugin that takes an SRT file, fetches it and convert it so it can be fed into `player.addRemoteTextTrack()`.
The code is roughly based on our styled-text-tracks & paced-transcript plugins and the conversion logic is inspired by https://github.com/silviapfeiffer/silviapfeiffer.github.io/blob/master/index.html#L150
> feat: support srt subtitle format

- package.json
- src/config/defaults.js
- src/plugins/chapters/chapters.js
- src/plugins/paced-transcript/index.js
- src/plugins/srt-text-tracks/srt-text-tracks.js
This PR disables `nativeTextTracks` in Safari.
We did everything possible to use the native text tracks, but we now realize it never worked good enough so falling back to our emulated text tracks.
> fix: programatic text-tracks in Safari

- test/e2e/specs/apiAndEventsPage.spec.ts
- test/e2e/src/pom/PageManager.ts
- test/e2e/src/pom/apiAndEventsPage.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17955
This test is navigating to api and events page (api.html) and make sure that video element is playing (checking that the video is not paused).
> me-17955: test if video on api and events page is playing

- test/e2e/specs/audioPlayerPage.spec.ts
- test/e2e/src/pom/PageManager.ts
- test/e2e/src/pom/audioPlayerPage.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17956
This test is navigating to audio player page (audio.html) and make sure that 2 videos element are playing (checking that the video is not paused).
> me-17956: test if videos on audio player page are playing

- test/e2e/components/BaseComponent.ts
- test/e2e/components/videoComponent.ts
- test/e2e/specs/autoplayOnScrollPage.spec.ts
- test/e2e/src/pom/PageManager.ts
- test/e2e/src/pom/autoplayOnScrollPage.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17957
This test is navigating to autoplay on scroll page (autoplay-on-scroll.html) and make sure that video is playing automatically on scroll.
First testing that the video is not playing (before scrolling), then scrolling until video element is visible and test that it is playing (checking that the video is not paused).
> me-17957: test if video on autoplay on scroll page is playing

- test/e2e/components/BaseComponent.ts
- test/e2e/components/videoComponent.ts
- test/e2e/specs/audioPlayerPage.spec.ts
- test/e2e/specs/autoplayOnScrollPage.spec.ts
- test/e2e/src/pom/audioPlayerPage.ts
- test/e2e/src/pom/autoplayOnScrollPage.ts
Running ESLint fix where needed.
> vp test: eslint fix

- src/config/defaults.js
- src/video-player.utils.js
Fixes a regression caused by [this change](https://github.com/videojs/video.js/blame/19ca3f2ebe0ec7f0374fa3bc7df1457f9f185823/src/js/control-bar/progress-control/seek-bar.js#L52) in videojs.
Now, our hacky work-around is not needed anymore, and we can simply configure the player to behave nicely on mobile.
> fix: seek-thumbs positioning

- test/e2e/components/videoComponent.ts
- test/e2e/specs/cldAnalyticsPage.spec.ts
- test/e2e/specs/codecsAndFormats.spec.ts
- test/e2e/src/pom/PageManager.ts
- test/e2e/src/pom/cldAnalyticsPage.ts
- test/e2e/src/pom/codecsAndFormats.ts
Relevant tasks - https://cloudinary.atlassian.net/browse/ME-17959 and https://cloudinary.atlassian.net/browse/ME-17960
The PR includes 2 tests:
1. Navigating to Cloudinary analytics page (cloudinary-analytics.html) and make sure that 4 videos element are playing (checking that the video is not paused).
2. Navigating to codecs and formats page (codec-formats.html) and make sure that 3 videos element are playing (checking that the video is not paused).
> me-17959: test if videos on Cloudinary analytics and codecs and formats pages are playing

- test/e2e/specs/colorsApiPage.spec.ts
- test/e2e/src/pom/PageManager.ts
- test/e2e/src/pom/colorsApiPage.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17961
This test is navigating to colors API page (colors.html) and make sure that 3 videos element are playing (checking that the video is not paused).
> me-17961: test if videos on colors api page are playing

- test/e2e/specs/componentsPage.spec.ts
- test/e2e/src/pom/PageManager.ts
- test/e2e/src/pom/componentsPage.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17962
This test is navigating to components page (components.html) and make sure that video element is playing (checking that the video is not paused).
> me-17962: test if video on components page is playing

- test/e2e/components/videoComponent.ts
- test/e2e/specs/analyticsPage.spec.ts
- test/e2e/specs/apiAndEventsPage.spec.ts
- test/e2e/specs/audioPlayerPage.spec.ts
- test/e2e/specs/autoplayOnScrollPage.spec.ts
- test/e2e/specs/chaptersPage.spec.ts
- test/e2e/specs/cldAnalyticsPage.spec.ts
- test/e2e/specs/codecsAndFormats.spec.ts
- test/e2e/specs/colorsApiPage.spec.ts
- test/e2e/specs/componentsPage.spec.ts
- test/e2e/specs/displayConfigurationsPage.spec.ts
- test/e2e/specs/highlightsGraphPageVideoIsPlaying.spec.ts
- test/e2e/specs/mainPageVideoIsPlaying.spec.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-18581
A new function was added to video component - validateVideoIsPlaying.
The new function validates whether the video is currently playing.This method uses the `isPaused` function to determine the current state of the video.
expectedPlaying - A boolean indicating the expected playback state of the video. Pass `true` if the video is expected to be playing, or `false` if it is expected to be paused.
The task was refactoring relevant specs and replace isPaused()).toEqual(false) with validateVideoIsPlaying(true)
> me-18581: refactor specs to use validateVideoIsPlaying

- test/e2e/specs/fluidLayoutsPage.spec.ts
- test/e2e/src/pom/PageManager.ts
- test/e2e/src/pom/fluidLayoutsPage.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17965
This test is navigating to fluid layouts page (fluid.html) and make sure that video element is playing.
> Me 17965 - fluid layout page video playing

- test/e2e/specs/forceHlsSubtitlesPage.spec.ts
- test/e2e/src/pom/PageManager.ts
- test/e2e/src/pom/forceHlsSubtitlesPage.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17966
This test is navigating to force HLS subtitles page (force-hls-subtitles-ios.html) and make sure that video element is playing.
> me-17966: test if video on force HLS subtitles page is playing

- test/e2e/specs/playlistPage.spec.ts
- test/e2e/src/pom/PageManager.ts
- test/e2e/src/pom/playlistPage.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17968
This test is navigating to playlist page (playlist.html) and make sure that videos element are playing.
> me-17968 test if videos on playlist page are playing

- test/e2e/components/videoComponent.ts
- test/e2e/specs/cldAnalyticsPage.spec.ts
- test/e2e/specs/playlistByTagPage.spec.ts
- test/e2e/src/pom/PageManager.ts
- test/e2e/src/pom/playlistByTagPage.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17969
This test is navigating to playlist by tag page (playlist-by-tag-captions.html) and make sure that video element is playing.
> me-17969: test if video on playlist by tag page is playing

- test/e2e/specs/autoplayOnScrollPage.spec.ts
- test/e2e/specs/chaptersPage.spec.ts
- test/e2e/specs/cldAnalyticsPage.spec.ts
- test/e2e/specs/codecsAndFormats.spec.ts
- test/e2e/specs/colorsApiPage.spec.ts
- test/e2e/specs/multiplePlayersPage.spec.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-18661
Some of the specs of checking if video is playing became flaky as it take some time to the video to start autoplay.
toPass wrap was added to validateVideoIsPlaying function.
This PR is to remove the toPass wrap from existing specs
> me-18661: remove toPass wrap from existing specs

- test/e2e/specs/profilesPage.spec.ts
- test/e2e/src/pom/PageManager.ts
- test/e2e/src/pom/profilesPage.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17971
This test is navigating to profiles page (profiles.html) and make sure that videos element are playing.
> me-17971: test if videos on profiles page are playing

- test/e2e/specs/subtitlesAndCaptionsPage.spec.ts
- test/e2e/src/pom/PageManager.ts
- test/e2e/src/pom/subtitlesAndCaptionsPage.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17976
This test is navigating to subtitles and captions page (subtitles-and-captions.html) and make sure that videos element are playing.
> me-17976: tests if videos are playing on subtitles and captions page

- test/e2e/specs/videoTransformationsPage.spec.ts
- test/e2e/src/pom/PageManager.ts
- test/e2e/src/pom/videoTransformationsPage.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17977
This test is navigating to video transformations page (transformations.html) and make sure that videos element are playing.
> me-17977: tests if videos are playing on video transformations page

- test/e2e/components/videoComponent.ts
- test/e2e/specs/vastAndVpaidPage.spec.ts
- test/e2e/src/pom/PageManager.ts
- test/e2e/src/pom/vastAndVpaidPage.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17978
This test is navigating to vast and vpaid page (vast-vpaid.html) and make sure that videos element are playing.
New optional parameter called `timeout` was added to `validateVideoIsPlaying` function because this page tests ads before videos and we need to wait minimum of 10 seconds until the ad finishes and the videos is starting. In all other cases `timeout` is set to default of 3 seconds.
> me-17978: tests if videos are playing on vast and vpaid page

- .github/workflows/e2e_pr.yml
- test/e2e/specs/vastAndVpaidPage.spec.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-18899
Currently when the E2E fails the report is not being pushed to repository and not written in url summary.
This PR is to fix it and get it push on success and failure.
> me-18899: fix push report to repository in case of failure

- README.md
- src/assets/styles/main.scss
- src/assets/styles/mixins/skin.scss
This PR fixes the Big Play Button focus indication along with better defaults for dark/light skins
Before:
After:
> fix: Focus Visible (WCAG 2.4.7)

- docs/colors.html
- docs/multiple-players.html
- src/assets/styles/components/title-bar.scss
- src/plugins/chapters/chapters.scss
- src/plugins/colors/index.js
- src/plugins/playlist/ui/playlist.scss
- src/plugins/playlist/ui/thumbnail/thumbnail.scss
- src/video-player.utils.js
- test/e2e/src/pom/colorsApiPage.ts
- test/e2e/src/pom/multiplePlayersPage.ts
This PR fixes a few text color-contrast issues
Before:
After:
> fix: Contrast (Minimum) (WCAG SC 1.4.3)

- src/assets/styles/main.scss
- src/plugins/colors/index.js
This PR fixes an issue with the volume slider track color-contrast
Before:
After:
> fix: Non-text contrast (WCAG 1.4.11)

- test/e2e/specs/ESM/esmMainPageVideoIsPlaying.spec.ts
- test/e2e/specs/NonESM/mainPageVideoIsPlaying.spec.ts
- test/e2e/specs/commonSpecs/mainPageVideoPlaying.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17983
This test is navigating to ESM main page and make sure that video element are playing.
As it share common steps as mainPageVideoIsPlaying.spec.ts that was already implemented I created common spec function testMainPageVideoIsPlaying and using it on both specs.
> me-17983: test if video is playing on ESM examples main page

- test/e2e/specs/ESM/esmHighlightsGraphPage.spec.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17985
This test is navigating to ESM highlights page (highlights-graph) and make sure that video element is playing.
> me-17985 test if video is playing on ESM highlights graph page

- test/e2e/specs/ESM/esmApiAndEventsPage.spec.ts
- test/e2e/specs/NonESM/apiAndEventsPage.spec.ts
- test/e2e/specs/commonSpecs/apiAndEventsPageVideoPlaying.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17987
This test is navigating to ESM events and API page and make sure that video element is playing.
As it share common steps as `apiAndEventsPage.spec.ts` that was already implemented I created common spec function `testApiAndEventsPageVideoIsPlaying` and using it on both specs.
> me-17987: test if video is playing on ESM events and api page

- docs/es-modules/audio.html
- test/e2e/specs/ESM/esmAudioPlayerPage.spec.ts
- test/e2e/specs/NonESM/audioPlayerPage.spec.ts
- test/e2e/specs/commonSpecs/audioPlayerPageVideoPlaying.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17988
This test is navigating to ESM audio player page and make sure that video elements are playing.
As it share common steps as `audioPlayerPage.spec.ts` that was already implemented I created common spec function `testAudioPlayerPageVideosArePlaying` and using it on both specs.
> ME-17988: test if videos are playing on audio player page

- test/e2e/specs/ESM/esmAutoplayOnScroll.spec.ts
- test/e2e/specs/NonESM/autoplayOnScrollPage.spec.ts
- test/e2e/specs/commonSpecs/autoplayOnScrollVideoPlaying.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17989
This test is navigating to ESM autoplay on scroll and make sure that video element is playing.
As it share common steps as `autoplayOnScrollPage.spec.ts` that was already implemented I created common spec function `testAutoplayOnScrollPageVideoIsPlaying` and using it on both specs.
> Me 17989 esm autoplay on scroll page video playing

- test/e2e/specs/ESM/esmChaptersPage.spec.ts
- test/e2e/specs/NonESM/chaptersPage.spec.ts
- test/e2e/specs/commonSpecs/chaptersPage.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17990
This test is navigating to ESM chapters page and make sure that videos element are playing.
As it share common steps as `chaptersPage.spec.ts` that was already implemented I created common spec function `testChaptersPageVideosArePlaying` and using it on both specs.
> me-17990: test if videos are playing on ESM chapters page

- src/assets/styles/main.scss
Control bar box-shadow was appearing even when `controls: false`
https://cloudinary.atlassian.net/browse/ME-19325
> fix: controlbar shadow when controls: false

- test/e2e/specs/ESM/esmCodecsAndFormatsPage.spec.ts
- test/e2e/specs/NonESM/codecsAndFormats.spec.ts
- test/e2e/specs/commonSpecs/codecsAndFormatsVideoPlaying.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17992
This test is navigating to ESM codecs and formats page and make sure that video elements are playing.
As it share common steps as `codecsAndFormats.spec.ts` that was already implemented I created common spec function `testCodecsAndFormatsPageVideoIsPlaying` and using it on both specs.
> me-17992: test if videos are playing on ESM codecs and formats page

- test/e2e/specs/ESM/esmComponentsPage.spec.ts
- test/e2e/specs/NonESM/componentsPage.spec.ts
- test/e2e/specs/commonSpecs/componentsPageVideoPlaying.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17994
This test is navigating to ESM components page and make sure that video element is playing.
As it share common steps as `componentsPage.spec.ts` that was already implemented I created common spec function `testComponentsPageVideoIsPlaying` and using it on both specs.
> me-17994: test if video is playing on ESM components page

- docs/es-modules/ui-config.html
- test/e2e/specs/ESM/esmDisplayConfigurationPage.spec.ts
- test/e2e/specs/NonESM/displayConfigurationsPage.spec.ts
- test/e2e/specs/commonSpecs/displayConfigurationPageVideoPlaying.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17995
This test is navigating to ESM display configuration page and make sure that video element is playing.
As it share common steps as `displayConfigurationsPage.spec.ts` that was already implemented I created common spec function `testDisplayConfigurationPageVideoIsPlaying` and using it on both specs.
Also added autoplay attribute to video element on ESM display configuration page to be the same as the equivalent base example page (https://cloudinary.github.io/cloudinary-video-player/ui-config.html)
> me-17995: test if video is playing on ESM display configuration page

- test/e2e/specs/ESM/esmFluidLayoutsPage.spec.ts
- test/e2e/specs/commonSpecs/fluidLayoutsPageVideoPlaying.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17997
This test is navigating to ESM fluid layouts player page and make sure that video element is playing.
As it share common steps as `fluidLayoutsPage.spec.ts` that was already implemented I created common spec function `testFluidLayoutsPageVideoIsPlaying` and using it on both specs.
> me-17997: test if video is playing on ESM fluid layouts page

- docs/es-modules/force-hls-subtitles.html
- test/e2e/specs/ESM/esmForceHlsSubtitlesPage.spec.ts
- test/e2e/specs/NonESM/forceHlsSubtitlesPage.spec.ts
- test/e2e/specs/commonSpecs/forceHlsSubtitlesPageVideoPlaying.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17998
This test is navigating to ESM force HLS subtitles page and make sure that video element is playing.
As it share common steps as `forceHlsSubtitlesPage.spec.ts `that was already implemented I created common spec function `testForceHlsSubtitlesPageVideoIsPlaying` and using it on both specs.
Also added autoplay attribute to video element on ESM force HLS subtitles page page to be the same as the equivalent base example page (https://cloudinary.github.io/cloudinary-video-player/force-hls-subtitles-ios.html)
> me-17998: test if video is playing on ESM force HLS subtitles page

- src/plugins/visual-search/components/SearchButton.js
- src/plugins/visual-search/components/SearchInput.js
- src/plugins/visual-search/components/SearchResults.js
- src/plugins/visual-search/visual-search.js
- src/plugins/visual-search/visual-search.scss
This PR improves a few aspects of using the visual-search plugin with a keyboard.
- Button has a visible focus highlight
- Input and X are focusable only when visible
- Results marker are focusable and clickable
> fix: visual search plugin accessibility

- docs/es-modules/multiple-players.html
- test/e2e/specs/ESM/esmMultiplePlayersPage.spec.ts
- test/e2e/specs/NonESM/multiplePlayersPage.spec.ts
- test/e2e/specs/commonSpecs/multiplePlayersPageVideoPlaying.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17999
This test is navigating to ESM multiple players page and make sure that video elements are playing.
As it share common steps as `multiplePlayersPage.spec.ts` that was already implemented I created common spec function `testMultiplePlayersPageVideoIsPlaying` and using it on both specs.
Also added id's to videos elements on ESM multiple players page be the same as the equivalent base example page (https://cloudinary.github.io/cloudinary-video-player/multiple-players)
> me-17999: test if videos are playing on ESM multiple players page

- test/e2e/specs/ESM/esmPlaylistPage.spec.ts
- test/e2e/specs/NonESM/playlistPage.spec.ts
- test/e2e/specs/commonSpecs/playlistPageVideoPlaying.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-18000
This test is navigating to ESM playlist page and make sure that video elements are playing.
As it share common steps as `playlistPage.spec.ts` that was already implemented I created common spec function `testPlaylistPageVideoIsPlaying` and using it on both specs.
> me-18000: test if videos are playing on ESM playlist page

- docs/es-modules/raw-url.html
- test/e2e/specs/ESM/esmRawUrlPage.spec.ts
- test/e2e/specs/NonESM/rawUrlPage.spec.ts
- test/e2e/specs/commonSpecs/rawUrlPageVideoPlaying.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-18004
This test is navigating to ESM raw URL and make sure that video elements are playing.
As it share common steps as `rawUrlPage.spec.ts` that was already implemented I created common spec function `testRawUrlPageVideoIsPlaying` and using it on both specs.
Also changed id's of ADP video element to be the same as the equivalent base example page
> me-18004: test if videos are playing on ESM raw url page

- docs/es-modules/recommendations.html
- test/e2e/specs/ESM/esmRecommendationsPage.spec.ts
- test/e2e/specs/NonESM/recommendationsPage.spec.ts
- test/e2e/specs/commonSpecs/recommendationsPageVideoPlaying.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-18005
This test is navigating to ESM recommendations page and make sure that video element is playing.
As it share common steps as `recommendationsPage.spec.ts` that was already implemented I created common spec function `testRecommendationsPageVideoIsPlaying` and using it on both specs.
Also added autoplay attribute to video element to be the same as the equivalent base example page
> me-18005: test if video is playing on recommendations page

- docs/es-modules/seek-thumbs.html
- test/e2e/specs/ESM/esmSeekThumbnailsPage.spec.ts
- test/e2e/specs/NonESM/seekThumbnailsPage.spec.ts
- test/e2e/specs/commonSpecs/seekThumbnailsPageVideoPlaying.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-18006
This test is navigating to ESM seek thumbnails page and make sure that video element is playing.
As it share common steps as `seekThumbnailsPage.spec.ts` that was already implemented I created common spec function `testSeekThumbnailsPageVideoIsPlaying` and using it on both specs.
Also added autoplay attribute to video element to be the same as the equivalent base example page
> me-18006: test if video is playing on seek thumbnails page

- test/e2e/specs/ESM/esmShoppableVideosPage.spec.ts
- test/e2e/specs/NonESM/shoppableVideosPage.spec.ts
- test/e2e/specs/commonSpecs/shoppableVideosPageVideoPlaying.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-18007
This test is navigating to ESM shoppable videos page and make sure that video element is playing.
As it share common steps as `shoppableVideosPage.spec.ts` that was already implemented I created common spec function `testShoppableVideosPageVideoIsPlaying` and using it on both specs.
> me-18007: test if video is playing on esm shoppable videos page

- package-lock.json
- package.json
- src/assets/styles/main.scss
....
**This PR also bumps video.js version to latest (minor: 8.21.0 > 8.23.3)**
> fix: update quality selector check icon

- docs/es-modules/subtitles-and-captions.html
- test/e2e/specs/ESM/esmSubtitlesAndCaptionsPage.spec.ts
- test/e2e/specs/NonESM/subtitlesAndCaptionsPage.spec.ts
- test/e2e/specs/commonSpecs/subtitlesAndCaptionsPgaeVideoPlaying.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-18008
This test is navigating to ESM subtitles and captions page and make sure that video elements are playing.
As it share common steps as `subtitlesAndCaptionsPage.spec.ts` that was already implemented I created common spec function `testSubtitlesAndCaptionsPageVideoIsPlaying` and using it on both specs.
Also I removed autoplay to first video to be the same as the equivalent base example page.
> me-18008: test if video is playing on esm subtitles and captions page

- package-lock.json
- package.json
- src/plugins/cloudinary-analytics/index.js
Add new version of video analytics:
* use player adapter
* add live stream analytics
> feat: live streams analytics

- test/e2e/specs/ESM/esmVastAndVpaidPage.spec.ts
- test/e2e/specs/NonESM/vastAndVpaidPage.spec.ts
- test/e2e/specs/commonSpecs/vastAndVpaidPage.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-18010
This test is navigating to ESM vast and vpaid page and make sure that video elements are playing.
As it share common steps as `vastAndVpaidPage.spec.ts` that was already implemented I created common spec function `testVastAndVpaidPageVideoIsPlaying` and using it on both specs.
> me-18010: test if videos are playing on esm vast and vpaid page

- src/plugins/cloudinary/models/video-source/video-source.js
- src/video-player.const.js
This fixes the broken internal analytics config, a regression introduced in v3.x
The fix is based on a line-by-line comparison I did with [the previous version](https://github.com/cloudinary/cloudinary-video-player/blob/v2.6.0/src/video-player.const.js)
> fix: internal analytics

- src/player.js
This PR fixes an issue with cloud configurations not being passed correctly to the JS SDK for URL generation
> fix: secure_distribution not passed correctly when fetching profiles

- src/config/configSchema.json
- src/plugins/share/share.js
Public-ids with slashes were causing 404 errors.
Also, better spinner handling
> fix: filename generated for download button

- src/plugins/text-tracks-manager/index.js
- src/plugins/text-tracks-manager/utils.js
Remove text tracks fallback (we already have error visible if needed)
> fix: remove text tracks fallback

- src/plugins/adaptive-streaming/videojs-contrib-hlsjs.js
The new HLS engine was having issues with text-tracks defined via HLS manifest
> fix(VIDEO-20021): subtitles defined in HLS manifest
