cloudinary/cloudinary-video-player

- .gitignore
- package.json
- webpack/common.config.js
- yarn.lock
> Fix broken HLS in minified version

- package.json
- src/plugins/context-menu/components/context-menu.js
- src/plugins/context-menu/index.js
- src/utils/positioning.js
> Bound context menu to Player container

- .gitignore
- package.json
- yarn.lock
Otherwise `yarn install` is complaining
> Bump node-sass to ^4.7.2

- .eslintrc.js
- src/assets/styles/mixins/mixins.scss
- src/components/component-utils.js
- src/components/recommendations-overlay/recommendations-overlay-primary-item.js
- src/components/recommendations-overlay/recommendations-overlay.scss
Adjust recommendation styles to the design.
Make sure text never overflows
We will create the mobile layout in a following PR
> CLD-4723-description-cutoff

- src/assets/styles/main.scss
> CLD-5860-typography

- src/assets/styles/components/playlist.scss
- src/assets/styles/components/thumbnail.scss
- src/assets/styles/mixins/skin.scss
- src/components/recommendations-overlay/recommendations-overlay.scss
This PR handles:
* Titles truncation with an ellipsis
* Titles readability (background gradient in the dark theme)
* Duration positioning (duration data still missing, but styles are ready)
> CLD-5860 playlist titles

- src/plugins/cloudinary/components/cloudinary-button.js
This PR adds "muted" indication in the info tooltip
> CLD-7315-video-popup-mute

- src/assets/styles/videojs-ima.scss
This PR fixes a small CSS issue with the ad position.
> CLD-6861-vast-test

- src/assets/styles/main.scss
This PR removes the focus highlight from the player.
> CLD-7147-Blue-border-twisted

- src/assets/styles/videojs-ima.scss
This prevents the flash of next video while the ad loads
> CLD-4065-VAST-preroll

- src/plugins/ima/index.js
fixed ad shows as not muted when muted
> muted ad issue

- src/plugins/ima/index.js
@mikeys we did some testing to make sure none of the other layers or their order is affected by this.
> CLD-7957-Ad-overlay-ordering

- src/plugins/cloudinary/index.js
- src/plugins/cloudinary/models/audio-source.js
> Cld 7214 generate waveform image

- webpack/es5.config.js
- webpack/minified.config.js
- yarn.lock
removed the source map from builds
> removed sourceMap from dist build

- package.json
- src/plugins/cloudinary/index.js
- static/examples/components.html
- webpack/dev.config.js
added default crop method to the poster.
If with or height is specified and no crop method is given we add "scale" as a default
> added default crop method

- .babelrc
> Fix ie11 comparability

- src/video-player.js
> fix iOS ready state

- docs/360.html
- index.html
this is an example of using the player vr extension
> 360 example

- docs/adaptive-streaming.html
- package.json
- src/config/defaults.js
- src/plugins/cloudinary/common.js
- src/plugins/cloudinary/models/video-source.js
- src/video-player.js
- test/custom-error.test.js
- yarn.lock
Added support for video codecs in source types
reimplemented fallback to the original file and wrapped it with a setting skipFallback that is true by default.
> Apps 256 support codecs source types

- src/video-player.js
Revert the CORS fix to make it work.
> revert the fix for cors

- docs/custom-cld-errors.html
- src/config/defaults.js
- src/plugins/cloudinary/common.js
- src/plugins/cloudinary/index.js
- src/plugins/cloudinary/models/video-source.js
- src/utils/cloudinary.js
- src/video-player.js
removed the testUrl and added "getCldError"  on error
> removed test url

- docs/adaptive-streaming.html
- docs/scripts.js
- package.json
- src/plugins/index.js
- yarn.lock
> Apps 3377 add dashjs

- src/utils/cloudinary.js
> fix testing url with http

- src/video-player.js
- yarn.lock
fix switching sources with new text tracks
> clean text tracks before adding

- jest.config.js
- package.json
- src/plugins/cloudinary/index.js
- src/plugins/cloudinary/models/video-source.js
- src/utils/cloudinary.js
- test/videoSource.test.js
- yarn.lock
I added the fix for the adaptive no codec to here as well
> Apps 4410 transformation array

- docs/audio.html
- src/plugins/cloudinary/models/audio-source.js
This continues https://github.com/cloudinary/cloudinary-video-player/pull/163 with better example page
> APPS-4306-AudioSource-transformation

- docs/adaptive-streaming.html
- package.json
- src/plugins/dash/setup-audio-tracks.js
- src/plugins/dash/setup-text-tracks.js
- src/plugins/dash/videojs-dash.js
- src/plugins/index.js
- src/video-player.js
- yarn.lock
integrated and fixed videojs-contrib-dash into video-player
> Apps 4585 dash seeking

- docs/playlist.html
- docs/subtitles-and-captions.html
- src/assets/styles/main.scss
- src/plugins/cloudinary/index.js
- src/plugins/cloudinary/models/video-source.js
- src/plugins/cloudinary/playlist.js
- src/video-player.js
We were not handling captions in the playlist handler.
This PR fixes that and adds a test\example page
Also does a bit of CSS styling on the captions menu.
> Fix playlist-captions incompatibility

- docs/360.html
- docs/index.html
- docs/scripts.js
This PR:
* Adds light/non-minified to test pages version-selector UI for easier testing
* Improves selector UI
* Adds `Video Transformations` test page
* Fix CSS loader so it will always pull the correct version (was pulling full instead of light in some edge cases)
> APPS-4025-test-pages-b

- package.json
- src/components/shoppable-bar/layout/bar-layout.js
- src/components/shoppable-bar/layout/shoppable-panel-toggle.js
- src/components/shoppable-bar/panel/shoppable-panel-item.js
- src/components/shoppable-bar/panel/shoppable-panel.js
- src/utils/matches.js
- yarn.lock
This PR fixes Shoppable-videos on IE11
> APPS-5424-IE11 Shoppable Videos

- docs/index.html
- docs/raw-url.html
- jest.config.js
- src/plugins/cloudinary/models/video-source.js
- src/utils/cloudinary.js
- test/unit/videoSource.test.js
- yarn.lock
Added support for playing raw urls as a public_id
if video does not have an extension you need to add a sourceType with the type
I added unit tests for this feature as well.
@tsi please look at the example page I added.
> raw url support

- docs/shoppable.html
- src/components/shoppable-bar/panel/shoppable-panel.js
just a minor fix for the shoppable test page
> APPS-5865-debug-shoppable

- src/plugins/vtt-thumbnails/index.js
Fixes seek-thumbnails in IE11 (Promise polyfill)
> IE seek thumbnails fix

- src/utils/cloudinary.js
fixes missing subtitles in IE11
> change check vtt to work in IE11

- docs/raw-url.html
- src/plugins/dash/videojs-dash.js
- src/video-player.js
This is a quick fix to pass all errors from dash.js to video.js and fallback to the next source
> send every error from dashjs to videojs

- src/plugins/vtt-thumbnails/index.js
https://cloudinary.atlassian.net/browse/APPS-6725
> APPS-6725-seekThumb-folder-url

- package.json
- yarn.lock
@maoznir I configured only to check the minified versions
I configured the regular ver` max size to 470kb and the light to 105kb
you can change it as you see fit
> added bundlewatch

- src/video-player.js
this PR removes the streaming profile transformation from the VTT request
> APPS-8620-seekthumbs-stream-profile

- src/assets/styles/main.scss
https://cloudinary.atlassian.net/browse/APPS-5866
prevent the player, when fluid, from resizing `onReady` to 100% width
> APPS-5866-load-time-performance

- .eslintrc.js
- docs/interaction-area.html
- package.json
- src/assets/styles/main.scss
- src/utils/array.js
- src/utils/dom.js
- src/utils/type-inference.js
- src/video-player.js
- src/video-player.utils.js
This feature is a first step for 'Video Zoom'. 
There is a 'interaction-area' doc page.  (http://localhost:3000/interaction-area.html)
There isn't a link for that on the main page, customers should not have access to it yet.
https://user-images.githubusercontent.com/76470570/120180765-d8f4fa00-c214-11eb-9200-bff5bdcd60e1.mov
> APPS-9490 adding option for adding trackers area

- docs/interaction-area.html
- src/video-player.js
rename 'addTrackers' function to 'addInteractionAreas'
> rename addTrackers function to addInteractionAreas

- src/plugins/cloudinary/index.js
- src/utils/cloudinary.js
This is a workaround the problem described in the ticket 
https://cloudinary.atlassian.net/browse/APPS-9349
> work around safari hls h265 problem

- docs/interaction-area.html
- package.json
- src/assets/styles/main.scss
- src/plugins/cloudinary/models/video-source/video-source.const.js
- src/plugins/cloudinary/models/video-source/video-source.js
- src/video-player.const.js
- src/video-player.js
- src/video-player.utils.js
https://cloudinary.atlassian.net/browse/APPS-9674
You may take a look on 'http://localhost:3000/interaction-area.html' when running local dev
> Apps 9676 add support for custome vtt

- package.json
- src/components/logoButton/logo-button.const.js
- src/components/logoButton/logo-button.js
- src/components/playlist/components/upcoming-video-overlay.js
- src/components/playlist/playlist-widget.js
- src/components/playlist/playlist.const.js
- src/components/playlist/playlist.js
- src/components/shoppable-bar/layout/bar-layout.js
- src/components/shoppable-bar/layout/shoppable-panel-toggle.js
- src/components/shoppable-bar/layout/shoppable-products-overlay.js
- src/components/shoppable-bar/panel/shoppable-panel-item.js
- src/components/shoppable-bar/panel/shoppable-panel.js
- src/components/shoppable-bar/shoppable-post-widget.js
- src/components/shoppable-bar/shoppable-widget.const.js
- src/components/shoppable-bar/shoppable-widget.js
> more factoring

- docs/interaction-area.html
- src/video-player.const.js
- src/video-player.js
- src/video-player.utils.js
- zoom transformation calc fix
- rename templateName -> template
> zoom transformation calc fix

- package.json
- src/video-player.js
- webpack/dev.config.js
- yarn.lock
The player was not working in IE11
> re implement isObj to work in IE11

- src/plugins/dash/videojs-dash.js
> fix videos in dash not playing

- docs/interaction-area.html
- package.json
- src/assets/styles/components/interaction-areas.scss
- src/assets/styles/main.scss
- src/components/interaction-area/interaction-area.const.js
- src/components/interaction-area/interaction-area.utils.js
- src/utils/dom.js
- src/utils/time.js
- src/video-player.const.js
- src/video-player.js
- src/video-player.utils.js
- new look for interaction areas - [](https://cloudinary.atlassian.net/browse/APPS-9696 )
- update interaction areas position on resize (and fullscreen) - https://cloudinary.atlassian.net/browse/APPS-9846
https://user-images.githubusercontent.com/76470570/124092611-ba765e80-da5f-11eb-8f53-3246fcfc5184.mov
> Apps 9696 interaction areas display

- docs/interaction-area.html
- src/assets/styles/components/interaction-areas.scss
- src/components/interaction-area/interaction-area.utils.js
- src/video-player.js
- src/video-player.utils.js
- fix:  Video player - in some cases interaction area dots get stuck  , [https://cloudinary.atlassian.net/browse/APPS-10019](https://cloudinary.atlassian.net/browse/APPS-10019 )
- fix : Video player - 'first screen' disappears when video on autoplay mode : [https://cloudinary.atlassian.net/browse/APPS-10009](https://cloudinary.atlassian.net/browse/APPS-10009)
- Video player - after zoom out in full screen the interaction areas move (set manually) : [https://cloudinary.atlassian.net/browse/APPS-10020](https://cloudinary.atlassian.net/browse/APPS-10020)
> Fix more interaction areas bug

- docs/interaction-area.html
- src/assets/styles/components/interaction-areas.scss
- src/components/interaction-area/interaction-area.const.js
- src/components/interaction-area/interaction-area.utils.js
- src/utils/dom.js
https://cloudinary.atlassian.net/browse/APPS-10060
https://user-images.githubusercontent.com/76470570/126134790-9017ddc3-6707-4676-a6b5-f14c021643a9.mov
approved by ui/ux (Dalit)
> Add pulse animation to the dots on video zoom

- src/assets/styles/components/interaction-areas.scss
- src/assets/styles/components/themedButton.scss
- src/assets/styles/main.scss
- src/components/interaction-area/interaction-area.const.js
- src/components/interaction-area/interaction-area.utils.js
- src/components/themeButton/themedButton.const.js
- src/components/themeButton/themedButton.js
- src/utils/dom.js
- src/video-player.js
APPS-10128
The ux/ui (Dalit) saw this an approved
https://user-images.githubusercontent.com/76470570/126596312-5dbbdb0a-62f1-4914-b44a-12974c07253c.mov
> improve ia layout message

- src/assets/styles/components/interaction-areas.scss
- src/components/interaction-area/interaction-area.utils.js
This is the jira ticket : https://cloudinary.atlassian.net/browse/APPS-10140.
The problem is since the elements are been added to the dom dynamically there is a small delay time till the css has been implemented.
> prevent css glitch for interaction-areas-container

- src/video-player.js
https://cloudinary.atlassian.net/browse/APPS-9829
> Apps 9829 video not working if ga script is not present

- docs/interaction-area.html
- package.json
- src/assets/styles/components/interaction-areas.scss
- src/assets/styles/components/themedButton.scss
- src/components/interaction-area/interaction-area.utils.js
- src/utils/object.js
- src/video-player.js
- test/unit/utils.test.js
https://cloudinary.atlassian.net/browse/APPS-10160
and 
https://cloudinary.atlassian.net/browse/APPS-10068 , changing the image css to : 
width: 60px;
height: 60px;
margin-bottom: 20px;
> Changing video-player interactionAreas config

- src/plugins/cloudinary/models/video-source/video-source.utils.js
- src/utils/array.js
- test/unit/videoSource.test.js
https://cloudinary.atlassian.net/browse/APPS-10182
> isCodecAlreadyExist fix

- package.json
- src/components/interaction-area/interaction-area.const.js
- src/components/interaction-area/interaction-area.utils.js
- src/config/defaults.js
- src/plugins/floating-player/index.js
- src/utils/type-inference.js
- src/validators/validators-functions.js
- src/validators/validators-types.js
- src/validators/validators.js
- src/video-player.const.js
- src/video-player.js
- src/video-player.utils.js
- test/isValidConfig.test.js
Add validators, the be sure the configuration object is valid. 
https://cloudinary.atlassian.net/browse/APPS-10246
> APPS-10246 - Add validators for video player configs

- package.json
- src/components/interaction-area/interaction-area.service.js
- src/video-player.js
- move all interaction-areas logic out of 'video-player.js' to it own file
- remove interaction-area from the 'light' version
> move the interaction-area logic to a different file

- docs/interaction-area.html
- src/components/interaction-area/interaction-area.service.js
- src/utils/array.js
- src/validators/validators-functions.js
- src/validators/validators-types.js
- src/validators/validators.js
- src/video-player.js
- test/isValidConfig.test.js
https://cloudinary.atlassian.net/browse/APPS-10316
> Apps 10327 interaction areas as config and not a function 

- src/components/interaction-area/interaction-area.service.js
https://cloudinary.atlassian.net/browse/APPS-9898
> APPS-9898 interaction area with non exist video URL bug fix

- src/components/interaction-area/interaction-area.service.js
- src/components/playlist/components/upcoming-video-overlay.js
- src/components/playlist/layout/playlist-layout.js
- src/components/playlist/panel/playlist-panel.js
- src/components/playlist/playlist-widget.js
- src/components/shoppable-bar/layout/bar-layout.js
- src/components/shoppable-bar/layout/shoppable-panel-toggle.js
- src/components/shoppable-bar/layout/shoppable-products-overlay.js
- src/components/shoppable-bar/panel/shoppable-panel.js
- src/components/shoppable-bar/shoppable-widget.js
- src/extended-events.js
- src/plugins/analytics/index.js
- src/plugins/cloudinary/models/audio-source/audio-source.js
- src/plugins/cloudinary/models/video-source/video-source.js
- src/utils/consts.js
- src/video-player.js
define events strings as constants
https://cloudinary.atlassian.net/browse/APPS-10607
> APPS-10607 - Define events strings as const

- package.json
- src/video-player.utils.js
- yarn.lock
https://cloudinary.slack.com/archives/C9B1DMFV3/p1638468005034600
> APPS-11107 - escape video tag id before passing to querySelector

- src/video-player.js
https://cloudinary.atlassian.net/browse/APPS-11176
handle an error on a safari
> APPS-11176 - handle an error on safari

- src/plugins/dash/videojs-dash.js
https://cloudinary.atlassian.net/browse/APPS-11283
> APPS-11283 - ERROR: Invalid Arguments

- src/plugins/dash/videojs-dash.js
https://cloudinary.atlassian.net/browse/APPS-11283
> APPS-11283 ERROR Invalid Arguments take2

- package.json
- yarn.lock
> fix: APPS-11227 updating video.js version

- src/components/playlist/playlist.js
Fixes https://cloudinary.atlassian.net/browse/APPS-11321
> APPS-11321-playlist-controls

- src/components/shoppable-bar/layout/shoppable-products-overlay.js
- src/components/shoppable-bar/shoppable-widget.scss
fixes https://cloudinary.atlassian.net/browse/APPS-10152
> APPS-10152-shoppable-hotspots-overlay-size

- package.json
- src/plugins/context-menu/components/context-menu-item.js
- src/plugins/context-menu/components/context-menu.js
- src/plugins/context-menu/contextMenuContent.js
- src/plugins/context-menu/index.js
- src/plugins/context-menu/videojs-contextmenu.js
- yarn.lock
https://cloudinary.atlassian.net/browse/APPS-11554
> APPS-11554-context-menu

- src/plugins/cloudinary/index.js
- src/validators/validators.js
- src/video-player.const.js
https://cloudinary.atlassian.net/browse/APPS-11761
> APPS-11862 - Adding integration param to the Video Player

- package.json
- src/index.js
- src/plugins/cloudinary/common.js
- src/utils/object.js
- src/video-player.const.js
- pick config param
- remove chainTarget prop from transformation object
> ads bug fix

- package.json
- src/components/interaction-area/interaction-area.service.js
https://cloudinary.atlassian.net/browse/APPS-1199
Before
https://user-images.githubusercontent.com/76470570/156560693-0a51b61c-4153-4ded-bf77-6bd6914fb21e.mov
After
https://user-images.githubusercontent.com/76470570/156560706-f77de184-c9a4-41fe-bb92-6b722592052f.mov
> APPS-11994 - Video player with interactionArea + Ad issue

- package.json
- yarn.lock
https://cloudinary.atlassian.net/browse/POP-7399
Update Cloudinary sdk to fix support start_offset and end_offset
> fix: POP-7399 offset_start and offset_end sdk update

- src/video-player.js
https://cloudinary.atlassian.net/browse/POP-7978
> POP-7978 - HLS and playlist issues

- docs/cloudinary-analytics.html
- docs/index.html
- package.json
- src/components/cld-analytics/cld-analytics.js
- src/components/cld-analytics/events.consts.js
- src/components/cld-analytics/send-beacon-request.js
- src/config/defaults.js
- src/index.js
- src/plugins/cloudinary-analytics/index.js
- src/plugins/index.js
- src/validators/validators.js
- src/video-player.const.js
- src/video-player.js
- yarn.lock
New feature - Cloudinary video analytics
Core functionality is in components - we can use it outside cloudinary-video-player with any video player - we just need to provide basic data (HTML video tag ref and metadata - cloudName and videoPublicId).
> Me 3833 cld analytics

- src/components/interaction-area/interaction-area.service.js
- src/plugins/dash/index.js
- src/utils/time.js
- src/video-player.js
Story: https://cloudinary.atlassian.net/browse/ME-4802
> ME-4804-prevent-error-while-lazy-loading

- package.json
- yarn.lock
Resolve critical vulnerability
> fix: videojs bump & reload yarn lock

- src/config/defaults.js
Make Cld analytics opt-out (by default turned on).
> Me 5531 default cld analytics

- src/components/cld-analytics/cld-analytics.js
Send video duration for cld analytics.
> feat: send video duration for cld analytics

- src/components/logoButton/logo-button.js
> fix: add aria label to logo link

- src/config/defaults.js
Jira: https://cloudinary.atlassian.net/browse/ME-6565
> ME-6565: enable seek thumbs by default

- docs/components.html
- src/plugins/videojs-http-source-selector/plugin.js
- src/plugins/vtt-thumbnails/vtt-thumbnails.scss
- src/video-player.js
This PR fixes seek-thumbs compatibility with playlist coming-up & recommendations
> ME-6565-seek-thumbs-by-default-2

- package.json
Jira: https://cloudinary.atlassian.net/browse/ME-5533
> ME-5533: add files & types to package.json

- src/assets/styles/main.scss
- src/config/defaults.js
Jira: https://cloudinary.atlassian.net/browse/ME-6348
> ME-6348-captions-accessibility

- docs/histogram.html
- docs/index.html
- src/assets/styles/main.scss
- src/config/defaults.js
- src/plugins/colors/index.js
- src/plugins/histogram/histogram.scss
- src/plugins/histogram/index.js
- src/plugins/index.js
- src/plugins/vtt-thumbnails/index.js
- src/validators/validators.js
- src/video-player.const.js
- src/video-player.js
This PR adds a plugin to display a histogram chart on the progress bar.
> ME-6929-histogram-plugin

- docs/index.html
- package.json
- src/index.js
- src/utils/object.js
- src/utils/string.js
- src/video-player.const.js
- src/video-player.js
This PR adds support for camelCase cld configuration alongside snake_case configs like it did before.
https://cloudinary.atlassian.net/browse/ME-4810
> ME-4810-support-cloudName

- src/utils/get-analytics-player-options.js
- src/video-player.js
Small adjustments to code of internal analytics
> fix: internal analytics adjustments

- package.json
- yarn.lock
> fix: bump cld analytics package

- src/video-player.js
* add missing `cloudName` to init request
* make init request ONLY when there is source (playlist/source)
* change param `vp_version` to `vpVersion`
> fix: add missing props to init request

- package.json
- src/assets/styles/main.scss
- types/video-player.d.ts
- yarn.lock
Update a minor VideoJS version to get rid of dependency-tree conflicts
> ME-13693-update-videojs

- types/video-player.d.ts
This reverts commit a160c08481fd6acb432c879aa98d8672374c1c6c.
> ME-13693-update-videojs - Revert "types"

- package.json
- src/plugins/cloudinary-analytics/index.js
- yarn.lock
Add custom props to cloudinary analytics.
> feat: custom props to cld analytics

- docs/chapters.html
- docs/index.html
- package-lock.json
- package.json
- src/assets/styles/main.scss
- src/components/interaction-area/interaction-area.service.js
- src/components/playlist/panel/playlist-panel-item.js
- src/components/playlist/panel/playlist-panel.js
- src/components/playlist/playlist-widget.js
- src/components/playlist/thumbnail/thumbnail.js
- src/components/qualitySelector/qualitySelector.js
- src/components/shoppable-bar/shoppable-widget.js
- src/config/defaults.js
- src/extended-events.js
- src/plugins/ai-highlights-graph/index.js
- src/plugins/analytics/index.js
- src/plugins/chapters/chapters.scss
- src/plugins/chapters/index.js
- src/plugins/context-menu/components/context-menu.js
- src/plugins/context-menu/videojs-contextmenu.js
- src/plugins/dash/videojs-dash.js
- src/plugins/index.js
- src/plugins/videojs-http-source-selector/plugin.js
- src/plugins/vtt-thumbnails/index.js
- src/plugins/vtt-thumbnails/vtt-thumbnails.scss
- src/video-player.const.js
- src/video-player.js
- src/video-player.utils.js
This PR introduces a new chapters plugin.
ToDo:
* ✅ Refactor vtt-thumbnails to use core videojs functionality - mouse tracking, DOM components
* ✅ Progress bar markers
* ✅ Progress bar chapters display (on hover)
* ✅ Control bar current chapter display
* ✅ Allow inline chapters (VTT alternative)
* ✅ Look into console warnings
> ME-6707-chapters

- src/plugins/cloudinary-analytics/index.js
Run analytics also on cld analytics change - not only basic source change.
> fix: re-run analytics also on cld source change

- docs/chapters.html
- src/plugins/chapters/index.js
- src/plugins/cloudinary/models/video-source/video-source.const.js
- src/plugins/cloudinary/models/video-source/video-source.js
- src/plugins/vtt-thumbnails/index.js
- src/validators/validators.js
- src/video-player.js
Allow chapters to be configured at the source level.
> ME-13971-chapters-source

- src/plugins/chapters/index.js
- src/video-player.js
Fix chapters interface when switching video sources
> ME-14018-playlist-chapters

- package-lock.json
- package.json
> chore: bump cld analytics package

- src/assets/styles/main.scss
This PR fixes popup menus scroll when overflowing
> ME-14040-scroll-subtitles

- src/utils/get-analytics-player-options.js
> ME-14242-internal-analytics-fix

- docs/chapters.html
- src/plugins/chapters/index.js
- src/validators/validators.js
- src/video-player.js
Add auto option for chapters in Video Player (vtt files taken by naming convention, created by chapters editor)
> feat: add auto option for chapters

- src/plugins/paced-transcript/index.js
Really wanted to find a better solution to this
> ME-14358-paced-transcript-safari

- src/components/jumpButtons/jump-10-minus.js
- src/components/jumpButtons/jump-10-plus.js
- src/components/playlist/components/playlist-button.js
- src/components/recommendations-overlay/recommendations-overlay-primary-item.js
- src/plugins/videojs-http-source-selector/components/SourceMenuButton.js
- src/video-player.utils.js
> ME-6001-vp-wave-a11y

- docs/subtitles-and-captions.html
- src/assets/styles/components/text-tracks.scss
- src/plugins/styled-text-tracks/styled-text-tracks.js
- src/plugins/styled-text-tracks/styled-text-tracks.scss
- src/validators/validators.js
- src/video-player.js
This PR adjust the styled-subtitles positioning method to be:
```
options: {
theme: "", // one of 'default', 'videojs-default', 'yellow-outlined', 'player-colors' & '3d'
fontFace: "", // any Google font
fontSize: "", // any CSS value
gravity: "", // i.e. 'top-left', 'center' etc
box: { // Object of x/y/width/height
x: "0%",
y: "0%",
width: "100%",
height: "100%"
},
style: { // Styles key-value object
color: "hotpink"
}
},
```
> ME-14565-subtitles-styles-gravity

- src/index.all.js
- src/plugins/interaction-areas/index.js
Add new lazy-loaded modules to default bundle
> ME-14386-lazy-interaction-areas

- src/config/defaults.js
- src/video-player.const.js
- src/video-player.js
This PR fixes the `allowUsageReport` configuration param to function as documented
> fix: allowUsageReport

- src/assets/styles/components/text-tracks.scss
- src/plugins/styled-text-tracks/index.js
- src/plugins/styled-text-tracks/styled-text-tracks.js
- src/plugins/styled-text-tracks/styled-text-tracks.scss
This PR was created Automatically.
Please approve and squash-merge it.
Before merging, make sure all the changes are listed in the squash-commit footer.
Format must be plain conventional-commit, one per line.
No `*` bullets and no `----` comments are allowed.
Commit footer format for release-please (see https://github.com/googleapis/release-please/tree/main?tab=readme-ov-file#what-if-my-pr-contains-multiple-fixes-or-features):
> chore: update master

- src/plugins/playlist/playlist.js
- src/plugins/playlist/utils/api.js
This PR fixes the issues found in https://cloudinary.atlassian.net/browse/ME-15923
> ME-15917-cleanup-utils fix: isPlainObject

- docs/debug.html
- docs/es-modules/debug.html
- docs/es-modules/index.html
- docs/es-modules/package-lock.json
- docs/index.html
- src/validators/validators-functions.js
This PR adds an example page for the `debug` mode
> fix: esm examples (ME-15925)

- webpack/common.config.js
- webpack/es6.config.js
This PR implements @jakub-roch findings regarding [webpack chunk loading global](https://webpack.js.org/configuration/output/#outputchunkloadingglobal)
> fix: webpack chunk loading global

- package-lock.json
- package.json
- src/plugins/cloudinary-analytics/index.js
Bump video analytics package version
Trigger source change event only once
> fix: bump video analytics, trigger analytics event only once

- .github/actions/node-setup/action.yml
- .github/workflows/e2e_pr.yml
Adding workflow and action to CI process
> vp test: adding workflow and action for CI

- docs/es-modules/profiles.html
- docs/profiles.html
> fix: profiles docs link

- docs/cloudinary-analytics.html
- docs/es-modules/cloudinary-analytics.html
- docs/es-modules/profiles.html
- docs/profiles.html
- package-lock.json
- package.json
- src/plugins/cloudinary-analytics/index.js
Fix: docs for profiles & analytics
analytics options
> fix: docs for profiles & analytics, analytics options

- src/player.js
- test/e2e/specs/linksConsoleErrorsEsmPage.spec.ts
Default secure option for new `player` method
> fix: default secure option for new method

- src/player.js
- src/video-player.const.js
- src/video-player.js
Add internal analytics about usage of new method & profiles feature
> feat: add internal analytics about new method & profiles

- src/utils/get-analytics-player-options.js
- src/video-player.js
This fixes the change made in https://github.com/cloudinary/cloudinary-video-player/pull/728/files
> fix: source analytics

- test/e2e/specs/chaptersPage.spec.ts
- test/e2e/src/pom/PageManager.ts
- test/e2e/src/pom/chaptersPage.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17958
This test is navigating to chapters page (chapters.html) and make sure that 3 videos element are playing (checking that the video is not paused).
> me-17958: test if videos on chapters page are playing

- package-lock.json
- package.json
Relevant task: https://cloudinary.atlassian.net/browse/ME-18654
Updating Playwright version to `1.49.1`
> me-18654: update Playwright version

- test/e2e/specs/multiplePlayersPage.spec.ts
- test/e2e/src/pom/PageManager.ts
- test/e2e/src/pom/multiplePlayersPage.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17967
This test is navigating to multiple players page (multiple-players.html) and make sure that videos element are playing.
> me-17967: test if videos on multiple players page are playing

- test/e2e/specs/posterOptionsPage.spec.ts
- test/e2e/src/pom/PageManager.ts
- test/e2e/src/pom/posterOptionsPage.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17970
This test is navigating to poster options page (poster.html) and make sure that videos element are playing.
> me-17970: test if videos on poster options page are playing

- test/e2e/specs/rawUrlPage.spec.ts
- test/e2e/src/pom/PageManager.ts
- test/e2e/src/pom/rawUrlPage.ts
Relevant task - https://cloudinary.atlassian.net/browse/ME-17972
This test is navigating to raw url page (raw-url.html) and make sure that videos element are playing.
> me-17972: test if videos on raw url page are playing

- src/plugins/cloudinary/common.js
This PR fixes the issue of the browser reporting that it can't play AV1
> fix: error with f_auto AV1

- src/plugins/cloudinary/models/video-source/video-source.js
Passing all of the `options` was too much, specifically `delivery_type` caused issues
> fix: private video poster image

- package-lock.json
- package.json
Bumping `cloudinary-video-player-profiles` package to `1.3.0`
> feat: bump video player profile package

- src/video-player.js
This PR fixes the font-face configuration that broke during our source/player/cloud configuration refactor
> fix: font-face configuration

- src/plugins/adaptive-streaming/adaptive-streaming.js
- src/plugins/cloudinary/index.js
- test/adaptive-streaming.test.js
- test/unit/videoSource.test.js
https://cloudinary.atlassian.net/browse/VIDEO-19984
fix an issue for withCredentials support on Version 3.x
> fix(VIDEO-19984): withCredentials support for new hls package

- src/plugins/text-tracks-manager/index.js
Remove text tracks notifications
> fix: remove text tracks notifications
